<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="11.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.17" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\KiaKooshar.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Identities\Authorization\" />
    <Folder Include="Features\Identities\Authentication\Handlers\Queries\" />
    <Folder Include="Features\Identities\Authentication\Requests\Queries\" />
    <Folder Include="Features\Identities\Authorization\Policies\Handlers\Commands\" />
    <Folder Include="Features\Identities\Authorization\Policies\Handlers\Queries\" />
    <Folder Include="Features\Identities\Authorization\Policies\" />
    <Folder Include="Features\Identities\Authorization\Permissions\Handlers\Queries\" />
    <Folder Include="Features\Identities\Authorization\Permissions\Requests\Queries\" />
    <Folder Include="Features\Identities\Authorization\Policies\Requests\Commands\" />
    <Folder Include="Features\Identities\Authorization\Policies\Requests\Queries\" />
    <Folder Include="Features\Identities\Authentication\Handlers\Commands\Logout\" />
    <Folder Include="Features\Identities\Authentication\Handlers\Commands\RevokeToken\" />
    <Folder Include="Features\Identities\Authentication\Handlers\Commands\RefreshToken\" />
    <Folder Include="Features\Identities\Authorization\Roles\Handlers\Commands\" />
    <Folder Include="Features\Identities\Authorization\Roles\Handlers\Queries\" />
    <Folder Include="Features\Identities\Authorization\Roles\Requests\Commands\" />
    <Folder Include="Features\Identities\Authorization\Roles\Requests\Queries\" />
    <Folder Include="Specifications\Identities\Authorization\" />
    <Folder Include="Validation\Authorization\" />
  </ItemGroup>

</Project>
